Fix yml #15 [semver:patch]
CircleCI-Public/azure-cli-orb pull request #16
Opened 2021-08-26 15:22 UTC by RonnyTite

### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [ ] Examples have been added for any significant new features
- [ ] README has been updated, if necessary

### Motivation, issues

This PR is fixing #15 

### Description

 
 
 The fix being to replace:
```
apt-get update
```
by
```
apt-get --allow-releaseinfo-change update
```

`--allow-releaseinfo-change` description :

> Allow the update command to continue downloading data from a repository which changed its information of the release contained in the repository indicating e.g a new major release. APT will fail at the update command for such repositories until the change is confirmed to ensure the user is prepared for the change.

Source: https://manpages.debian.org/unstable/apt/apt-get.8.en.html

2022-03-03 19:53 UTC, EricRibeiro requested changes
I appreciate the help!

2022-03-03 19:53 UTC, EricRibeiro commented on src/commands/install.yml
> +        $SUDO apt-get --allow-releaseinfo-change update && $SUDO apt-get -qqy install apt-transport-https
While this works, I believe it's better to be specific about what we allow. This way, we don't hide unexpected changes. That said, what do you think of replacing `--allow-releaseinfo-change-suite` with `--allow-releaseinfo-change`?

You can read more about it here: https://stackoverflow.com/a/68990841.

2022-03-03 19:53 UTC, EricRibeiro commented on src/commands/install.yml
> +        $SUDO apt-get --allow-releaseinfo-change update
Same as above.

2022-03-24 11:19 UTC, RonnyTite commented
@EricRibeiroThanks for the feedback. Changes done ;) you can take a new look

2022-03-24 15:01 UTC, EricRibeiro commented
One of the tests failed: https://app.circleci.com/pipelines/github/CircleCI-Public/azure-cli-orb/122/workflows/ac3c877b-3926-4a51-a68e-40146e1ab1b0/jobs/406?invite=true#step-101-50.

I'm not 100% sure without investigating but updating the [test's executor images](https://github.com/CircleCI-Public/azure-cli-orb/blob/master/.circleci/config.yml#L18) might do the trick. Both images used for testing this orb are [outdated](https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/). The newest versions are [cimg/go](https://circleci.com/developer/images/image/cimg/go) and [cimg/python](https://circleci.com/developer/images/image/cimg/python).

2022-03-24 23:03 UTC, EricRibeiro requested changes

2022-03-24 23:03 UTC, EricRibeiro commented on .circleci/config.yml
> +    executor: go
If we are changing the argument we are passing here, we also need to change the executor's name from `golang` to `go`: https://github.com/CircleCI-Public/azure-cli-orb/blob/master/.circleci/config.yml#L19

2022-03-25 02:03 UTC, EricRibeiro commented on .circleci/config.yml
> +      - image: cimg/go:1.18.0
The image tag here should be `1.18`. The tag `1.18.0` doesn't exist.

2022-03-25 23:01 UTC, EricRibeiro commented
Thank you, @RonnyTite ✌️ 

It's all looking good now. We still need to update that golang image from the tests, but it's outside this PR's scope.

I'll push that change later.

2022-03-25 23:01 UTC, EricRibeiro approved these changes

2022-03-25 23:01 UTC, merged

2022-03-25 23:06 UTC, EricRibeiro commented
v1.2.2 released with this fix: https://circleci.com/developer/orbs/orb/circleci/azure-cli?version=1.2.2.